apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources-secret
  namespace: jenkins
type: Opaque
stringData:
  other_datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.jenkins.svc.cluster.local:8000
