apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
  namespace: jenkins
data:
  alerting.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: User
        receivers:
          - uid: fe6z0kyggsg01b
            type: email
            settings:
              addresses: webmanager00001@gmail.com
              singleEmail: false
            disableResolveMessage: false
    groups:
      - orgId: 1
        name: Evaluation group
        folder: dashboards
        interval: 1m
        rules:
          - uid: ae6z0no6s9t6od
            title: High CPU
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: PBFA97CFB590B2093
                model:
                  datasource:
                      type: prometheus
                      uid: PBFA97CFB590B2093
                  editorMode: code
                  expr: |-
                      avg without (mode,cpu) ((
                        1 - rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100
                      )
                  hide: false
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params:
                              - 80
                          type: gt
                        operator:
                          type: and
                        query:
                          params:
                              - C
                        reducer:
                          params: []
                          type: last
                        type: query
                  datasource:
                      type: __expr__
                      uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 1m
            isPaused: false
            notification_settings:
              receiver: User
          - uid: ee6z0u09q03k0a
            title: 'Low Free RAM '
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: PBFA97CFB590B2093
                model:
                  editorMode: code
                  expr: node_memory_MemFree_bytes / (1024 * 1024)
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params:
                              - 500
                          type: lt
                        operator:
                          type: and
                        query:
                          params:
                              - C
                        reducer:
                          params: []
                          type: last
                        type: query
                  datasource:
                      type: __expr__
                      uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 1m
            isPaused: false
            notification_settings:
              receiver: User
