adminPassword: password

admin:
  existingSecret: grafana-admin-secret

service:
  type: LoadBalancer
  ports:
    http: 3000

datasources:
  enabled: true
  config:
    apiVersion: 1
    datasources:
      secretName: grafana-datasources-secret
