apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-contact-points
  namespace: jenkins
data:
  notifiers.yaml: |
    notifiers:
    - orgId: 1
      name: User
      receivers:
        - uid: fe6z0kyggsg01b
          type: email
          settings:
            addresses: webmanager00001@gmail.com
            singleEmail: false
          disableResolveMessage: false
