{
 "title": "Node dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU  Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg without (mode,cpu) (\n  (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes - node_filesystem_avail_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory (MB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}