name: Deploy Jenkins

on:
  workflow_dispatch:
    branches:
      - task_4

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save kubeconfig to file
        run: |
          echo ${{ secrets.KUBECONFIG }} | base64 -d > /tmp/config

      - name: Create namespace for jenkins
        env:
          KUBECONFIG: /tmp/config
        run: |
          kubectl get ns jenkins || kubectl create ns jenkins

      - name: Create PV for jenkins
        env:
          KUBECONFIG: /tmp/config
        run: |
          kubectl apply -f jenkins-volume.yaml

      - name: Remove kubeconfig info
        run: rm -f /tmp/config
